from . import Dailymedi
from . import Doctorsnews
from . import Doctorstimes
from . import Donga
from . import Hkn24
from . import Joongang
from . import Khanews
from . import Medicaltimes
from . import Medifonews
from . import Nursenews